//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetCoreTemplate.Web.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResource_en_GB {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource_en_GB() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("AspNetCoreTemplate.Web.Resources.SharedResource.en-GB", typeof(SharedResource_en_GB).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string CreateAddressDelivery {
            get {
                return ResourceManager.GetString("CreateAddressDelivery", resourceCulture);
            }
        }
        
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        internal static string AllAddressDelivery {
            get {
                return ResourceManager.GetString("AllAddressDelivery", resourceCulture);
            }
        }
        
        internal static string Purchase {
            get {
                return ResourceManager.GetString("Purchase", resourceCulture);
            }
        }
        
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        internal static string AllPurchasebyStatus {
            get {
                return ResourceManager.GetString("AllPurchasebyStatus", resourceCulture);
            }
        }
        
        internal static string SendEmail {
            get {
                return ResourceManager.GetString("SendEmail", resourceCulture);
            }
        }
        
        internal static string AllEmailSent {
            get {
                return ResourceManager.GetString("AllEmailSent", resourceCulture);
            }
        }
        
        internal static string Documents {
            get {
                return ResourceManager.GetString("Documents", resourceCulture);
            }
        }
        
        internal static string DetailsCourier {
            get {
                return ResourceManager.GetString("DetailsCourier", resourceCulture);
            }
        }
        
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        internal static string MenuCreate {
            get {
                return ResourceManager.GetString("MenuCreate", resourceCulture);
            }
        }
        
        internal static string DetailsReastaurant {
            get {
                return ResourceManager.GetString("DetailsReastaurant", resourceCulture);
            }
        }
        
        internal static string CourierApply {
            get {
                return ResourceManager.GetString("CourierApply", resourceCulture);
            }
        }
        
        internal static string RestaurantApplay_ {
            get {
                return ResourceManager.GetString("RestaurantApplay ", resourceCulture);
            }
        }
        
        internal static string Carriers {
            get {
                return ResourceManager.GetString("Carriers", resourceCulture);
            }
        }
        
        internal static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        internal static string ClientPolicy_ {
            get {
                return ResourceManager.GetString("ClientPolicy ", resourceCulture);
            }
        }
        
        internal static string Policy {
            get {
                return ResourceManager.GetString("Policy", resourceCulture);
            }
        }
        
        internal static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        internal static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        internal static string CreateCity {
            get {
                return ResourceManager.GetString("CreateCity", resourceCulture);
            }
        }
        
        internal static string AreaCreate {
            get {
                return ResourceManager.GetString("AreaCreate", resourceCulture);
            }
        }
        
        internal static string CreateStreet {
            get {
                return ResourceManager.GetString("CreateStreet", resourceCulture);
            }
        }
        
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        internal static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        internal static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        internal static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        internal static string Entrance {
            get {
                return ResourceManager.GetString("Entrance", resourceCulture);
            }
        }
        
        internal static string Flour {
            get {
                return ResourceManager.GetString("Flour", resourceCulture);
            }
        }
        
        internal static string Apartament {
            get {
                return ResourceManager.GetString("Apartament", resourceCulture);
            }
        }
        
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        internal static string Cities {
            get {
                return ResourceManager.GetString("Cities", resourceCulture);
            }
        }
        
        internal static string Areas {
            get {
                return ResourceManager.GetString("Areas", resourceCulture);
            }
        }
        
        internal static string Streets {
            get {
                return ResourceManager.GetString("Streets", resourceCulture);
            }
        }
        
        internal static string Locations {
            get {
                return ResourceManager.GetString("Locations", resourceCulture);
            }
        }
        
        internal static string LocationsObj {
            get {
                return ResourceManager.GetString("LocationsObj", resourceCulture);
            }
        }
        
        internal static string StreetsInThisArea {
            get {
                return ResourceManager.GetString("StreetsInThisArea", resourceCulture);
            }
        }
        
        internal static string CreateNewArea {
            get {
                return ResourceManager.GetString("CreateNewArea", resourceCulture);
            }
        }
        
        internal static string CreateNewStreet {
            get {
                return ResourceManager.GetString("CreateNewStreet", resourceCulture);
            }
        }
        
        internal static string GenerateAllAreasInSofia {
            get {
                return ResourceManager.GetString("GenerateAllAreasInSofia", resourceCulture);
            }
        }
        
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        internal static string CreateNewCategory {
            get {
                return ResourceManager.GetString("CreateNewCategory", resourceCulture);
            }
        }
        
        internal static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        internal static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        internal static string AreaInThisCity {
            get {
                return ResourceManager.GetString("AreaInThisCity", resourceCulture);
            }
        }
        
        internal static string CreateNewCourier {
            get {
                return ResourceManager.GetString("CreateNewCourier", resourceCulture);
            }
        }
        
        internal static string Couriers {
            get {
                return ResourceManager.GetString("Couriers", resourceCulture);
            }
        }
        
        internal static string Vehichles {
            get {
                return ResourceManager.GetString("Vehichles", resourceCulture);
            }
        }
        
        internal static string UploadImage {
            get {
                return ResourceManager.GetString("UploadImage", resourceCulture);
            }
        }
        
        internal static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        internal static string Birthday {
            get {
                return ResourceManager.GetString("Birthday", resourceCulture);
            }
        }
        
        internal static string MobilePhone {
            get {
                return ResourceManager.GetString("MobilePhone", resourceCulture);
            }
        }
        
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        internal static string Vehichle {
            get {
                return ResourceManager.GetString("Vehichle", resourceCulture);
            }
        }
        
        internal static string WorkingArea {
            get {
                return ResourceManager.GetString("WorkingArea", resourceCulture);
            }
        }
        
        internal static string ChangeStatus {
            get {
                return ResourceManager.GetString("ChangeStatus", resourceCulture);
            }
        }
        
        internal static string AllByUser {
            get {
                return ResourceManager.GetString("AllByUser", resourceCulture);
            }
        }
        
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        internal static string Restaurant {
            get {
                return ResourceManager.GetString("Restaurant", resourceCulture);
            }
        }
        
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        internal static string Delivery {
            get {
                return ResourceManager.GetString("Delivery", resourceCulture);
            }
        }
        
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        internal static string Preparation {
            get {
                return ResourceManager.GetString("Preparation", resourceCulture);
            }
        }
        
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        internal static string OrderId {
            get {
                return ResourceManager.GetString("OrderId", resourceCulture);
            }
        }
        
        internal static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        internal static string Promotion {
            get {
                return ResourceManager.GetString("Promotion", resourceCulture);
            }
        }
        
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        internal static string StatusInThisMoment {
            get {
                return ResourceManager.GetString("StatusInThisMoment", resourceCulture);
            }
        }
        
        internal static string NewStatus {
            get {
                return ResourceManager.GetString("NewStatus", resourceCulture);
            }
        }
        
        internal static string ChangeLocationRestaurant {
            get {
                return ResourceManager.GetString("ChangeLocationRestaurant", resourceCulture);
            }
        }
        
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        internal static string CreateNewRole {
            get {
                return ResourceManager.GetString("CreateNewRole", resourceCulture);
            }
        }
        
        internal static string LocationsInThisStreet {
            get {
                return ResourceManager.GetString("LocationsInThisStreet", resourceCulture);
            }
        }
        
        internal static string CreateNewLocation {
            get {
                return ResourceManager.GetString("CreateNewLocation", resourceCulture);
            }
        }
        
        internal static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        internal static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        internal static string SendDate {
            get {
                return ResourceManager.GetString("SendDate", resourceCulture);
            }
        }
        
        internal static string IsCourier {
            get {
                return ResourceManager.GetString("IsCourier", resourceCulture);
            }
        }
        
        internal static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }
        
        internal static string Decline {
            get {
                return ResourceManager.GetString("Decline", resourceCulture);
            }
        }
        
        internal static string SendTime {
            get {
                return ResourceManager.GetString("SendTime", resourceCulture);
            }
        }
        
        internal static string SendGridEmail {
            get {
                return ResourceManager.GetString("SendGridEmail", resourceCulture);
            }
        }
        
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        internal static string Post {
            get {
                return ResourceManager.GetString("Post", resourceCulture);
            }
        }
        
        internal static string AddRoleToUser {
            get {
                return ResourceManager.GetString("AddRoleToUser", resourceCulture);
            }
        }
        
        internal static string CitiesExist {
            get {
                return ResourceManager.GetString("CitiesExist", resourceCulture);
            }
        }
        
        internal static string UserData {
            get {
                return ResourceManager.GetString("UserData", resourceCulture);
            }
        }
        
        internal static string Body {
            get {
                return ResourceManager.GetString("Body", resourceCulture);
            }
        }
        
        internal static string CourierWaitToApprove {
            get {
                return ResourceManager.GetString("CourierWaitToApprove", resourceCulture);
            }
        }
        
        internal static string RestaurantWaitToApprove {
            get {
                return ResourceManager.GetString("RestaurantWaitToApprove", resourceCulture);
            }
        }
        
        internal static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        internal static string NoDocumentIn {
            get {
                return ResourceManager.GetString("NoDocumentIn", resourceCulture);
            }
        }
        
        internal static string DeleteDocumentByThisUser {
            get {
                return ResourceManager.GetString("DeleteDocumentByThisUser", resourceCulture);
            }
        }
        
        internal static string UploudNewDocument {
            get {
                return ResourceManager.GetString("UploudNewDocument", resourceCulture);
            }
        }
        
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        internal static string ActiveDocumentByThisUser {
            get {
                return ResourceManager.GetString("ActiveDocumentByThisUser", resourceCulture);
            }
        }
        
        internal static string CreateNewVehichle {
            get {
                return ResourceManager.GetString("CreateNewVehichle", resourceCulture);
            }
        }
        
        internal static string ByCity {
            get {
                return ResourceManager.GetString("ByCity", resourceCulture);
            }
        }
        
        internal static string ByArea {
            get {
                return ResourceManager.GetString("ByArea", resourceCulture);
            }
        }
        
        internal static string CariersInfo {
            get {
                return ResourceManager.GetString("CariersInfo", resourceCulture);
            }
        }
        
        internal static string Courier {
            get {
                return ResourceManager.GetString("Courier", resourceCulture);
            }
        }
        
        internal static string IsRestaurnat {
            get {
                return ResourceManager.GetString("IsRestaurnat", resourceCulture);
            }
        }
        
        internal static string SendEmailWhit {
            get {
                return ResourceManager.GetString("SendEmailWhit", resourceCulture);
            }
        }
        
        internal static string UploudFile {
            get {
                return ResourceManager.GetString("UploudFile", resourceCulture);
            }
        }
        
        internal static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        internal static string Searching {
            get {
                return ResourceManager.GetString("Searching", resourceCulture);
            }
        }
        
        internal static string AllCouriers {
            get {
                return ResourceManager.GetString("AllCouriers", resourceCulture);
            }
        }
        
        internal static string AllRestaurants {
            get {
                return ResourceManager.GetString("AllRestaurants", resourceCulture);
            }
        }
        
        internal static string AllOrders {
            get {
                return ResourceManager.GetString("AllOrders", resourceCulture);
            }
        }
        
        internal static string AllOrdersByData {
            get {
                return ResourceManager.GetString("AllOrdersByData", resourceCulture);
            }
        }
        
        internal static string ToDay {
            get {
                return ResourceManager.GetString("ToDay", resourceCulture);
            }
        }
        
        internal static string LastWeek {
            get {
                return ResourceManager.GetString("LastWeek", resourceCulture);
            }
        }
        
        internal static string LastMonth {
            get {
                return ResourceManager.GetString("LastMonth", resourceCulture);
            }
        }
        
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        internal static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
    }
}
