//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetCoreTemplate.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResource_bg_BG {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource_bg_BG() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AspNetCoreTemplate.Web.Resources.SharedResource.bg-BG", typeof(SharedResource_bg_BG).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За нас.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ние сме платформа която свързва клиента, ресторанта и куриера на едно място.
        ///Създаден през 2020 година, нашата компания има бурен и бърз растеж в условията на Панадемията. 
        ///За клиента е супер удобно защото не се налага да влиза и търси във всички сайтове в града а е достатъчно само да потърси в платформата това което иска и ние ще покажем богатият избор из между всички ресторанти в платформата.
        ///За ресторантите е лесно защото не са длъжни да подържат шофьор, автомобил, да плщат данъци и застраховки, да мисля [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Съществуващи документи към този Юзър.
        /// </summary>
        internal static string ActiveDocumentByThisUser {
            get {
                return ResourceManager.GetString("ActiveDocumentByThisUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адреси.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добави Роля към Юзер.
        /// </summary>
        internal static string AddRoleToUser {
            get {
                return ResourceManager.GetString("AddRoleToUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Админ панел.
        /// </summary>
        internal static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всички.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всички Адреси за Доставка.
        /// </summary>
        internal static string AllAddressDelivery {
            get {
                return ResourceManager.GetString("AllAddressDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всички по Юзер.
        /// </summary>
        internal static string AllByUser {
            get {
                return ResourceManager.GetString("AllByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всички Куриери.
        /// </summary>
        internal static string AllCouriers {
            get {
                return ResourceManager.GetString("AllCouriers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всички изпратени Email.
        /// </summary>
        internal static string AllEmailSent {
            get {
                return ResourceManager.GetString("AllEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всички Поръчки.
        /// </summary>
        internal static string AllOrders {
            get {
                return ResourceManager.GetString("AllOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всички Поръчки за дата.
        /// </summary>
        internal static string AllOrdersByData {
            get {
                return ResourceManager.GetString("AllOrdersByData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всички поръчки по статъс.
        /// </summary>
        internal static string AllPurchasebyStatus {
            get {
                return ResourceManager.GetString("AllPurchasebyStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всички Ресторанти.
        /// </summary>
        internal static string AllRestaurants {
            get {
                return ResourceManager.GetString("AllRestaurants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всички Юзъри.
        /// </summary>
        internal static string AllUsers {
            get {
                return ResourceManager.GetString("AllUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Апартамент.
        /// </summary>
        internal static string Apartament {
            get {
                return ResourceManager.GetString("Apartament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Одобри.
        /// </summary>
        internal static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зона.
        /// </summary>
        internal static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Създай Зона.
        /// </summary>
        internal static string AreaCreate {
            get {
                return ResourceManager.GetString("AreaCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зони в този Град.
        /// </summary>
        internal static string AreaInThisCity {
            get {
                return ResourceManager.GetString("AreaInThisCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зони.
        /// </summary>
        internal static string Areas {
            get {
                return ResourceManager.GetString("Areas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рожденна дата.
        /// </summary>
        internal static string Birthday {
            get {
                return ResourceManager.GetString("Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Съдържание.
        /// </summary>
        internal static string Body {
            get {
                return ResourceManager.GetString("Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Търсене на Куриер по Зона.
        /// </summary>
        internal static string ByArea {
            get {
                return ResourceManager.GetString("ByArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Търсене на Куриер по Град.
        /// </summary>
        internal static string ByCity {
            get {
                return ResourceManager.GetString("ByCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В този момент няма свободни позиции..
        /// </summary>
        internal static string CariersInfo {
            get {
                return ResourceManager.GetString("CariersInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Свободни позиции.
        /// </summary>
        internal static string Carriers {
            get {
                return ResourceManager.GetString("Carriers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категория.
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Промени локацията на Ресторанта.
        /// </summary>
        internal static string ChangeLocationRestaurant {
            get {
                return ResourceManager.GetString("ChangeLocationRestaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Промени статуса.
        /// </summary>
        internal static string ChangeStatus {
            get {
                return ResourceManager.GetString("ChangeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Градове.
        /// </summary>
        internal static string Cities {
            get {
                return ResourceManager.GetString("Cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Съществуващи Градове.
        /// </summary>
        internal static string CitiesExist {
            get {
                return ResourceManager.GetString("CitiesExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Град.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Клиентска политика на поверителност .
        /// </summary>
        internal static string ClientPolicy_ {
            get {
                return ResourceManager.GetString("ClientPolicy ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коментари.
        /// </summary>
        internal static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контакти.
        /// </summary>
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Куриер.
        /// </summary>
        internal static string Courier {
            get {
                return ResourceManager.GetString("Courier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Кандидатствай за Куриер .
        /// </summary>
        internal static string CourierApply {
            get {
                return ResourceManager.GetString("CourierApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Куриери .
        /// </summary>
        internal static string Couriers {
            get {
                return ResourceManager.GetString("Couriers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Куриери чакащи за Одобрение.
        /// </summary>
        internal static string CourierWaitToApprove {
            get {
                return ResourceManager.GetString("CourierWaitToApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Създай.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Създай Адрес за Доставка.
        /// </summary>
        internal static string CreateAddressDelivery {
            get {
                return ResourceManager.GetString("CreateAddressDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Създай Град.
        /// </summary>
        internal static string CreateCity {
            get {
                return ResourceManager.GetString("CreateCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Създай нова Зона .
        /// </summary>
        internal static string CreateNewArea {
            get {
                return ResourceManager.GetString("CreateNewArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Създай нова Категория.
        /// </summary>
        internal static string CreateNewCategory {
            get {
                return ResourceManager.GetString("CreateNewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Създай нов Куриер.
        /// </summary>
        internal static string CreateNewCourier {
            get {
                return ResourceManager.GetString("CreateNewCourier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Създай нова локация.
        /// </summary>
        internal static string CreateNewLocation {
            get {
                return ResourceManager.GetString("CreateNewLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Създай нова Роля.
        /// </summary>
        internal static string CreateNewRole {
            get {
                return ResourceManager.GetString("CreateNewRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Създай нова Улица .
        /// </summary>
        internal static string CreateNewStreet {
            get {
                return ResourceManager.GetString("CreateNewStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Създай ново Превозно средство .
        /// </summary>
        internal static string CreateNewVehichle {
            get {
                return ResourceManager.GetString("CreateNewVehichle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Създай Улица.
        /// </summary>
        internal static string CreateStreet {
            get {
                return ResourceManager.GetString("CreateStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отхвърли.
        /// </summary>
        internal static string Decline {
            get {
                return ResourceManager.GetString("Decline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изтрий.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Изтрии документ към този Юзър .
        /// </summary>
        internal static string DeleteDocumentByThisUser {
            get {
                return ResourceManager.GetString("DeleteDocumentByThisUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доставка.
        /// </summary>
        internal static string Delivery {
            get {
                return ResourceManager.GetString("Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пояснение.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Детайли.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Детайли на Куриера.
        /// </summary>
        internal static string DetailsCourier {
            get {
                return ResourceManager.GetString("DetailsCourier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Детайли на Ресторант .
        /// </summary>
        internal static string DetailsReastaurant {
            get {
                return ResourceManager.GetString("DetailsReastaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Документ.
        /// </summary>
        internal static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Документи.
        /// </summary>
        internal static string Documents {
            get {
                return ResourceManager.GetString("Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Свали.
        /// </summary>
        internal static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        internal static string Entrance {
            get {
                return ResourceManager.GetString("Entrance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Етаж.
        /// </summary>
        internal static string Flour {
            get {
                return ResourceManager.GetString("Flour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to От.
        /// </summary>
        internal static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пълно име.
        /// </summary>
        internal static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автоматично генереиране на всички Зони в София.
        /// </summary>
        internal static string GenerateAllAreasInSofia {
            get {
                return ResourceManager.GetString("GenerateAllAreasInSofia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Здравей.
        /// </summary>
        internal static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начална.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Снимка.
        /// </summary>
        internal static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инфо.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Одобрен Куриер ли е.
        /// </summary>
        internal static string IsCourier {
            get {
                return ResourceManager.GetString("IsCourier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Одобрен Ресторант ли е.
        /// </summary>
        internal static string IsRestaurnat {
            get {
                return ResourceManager.GetString("IsRestaurnat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Език.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Последният месец.
        /// </summary>
        internal static string LastMonth {
            get {
                return ResourceManager.GetString("LastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Последната седмица.
        /// </summary>
        internal static string LastWeek {
            get {
                return ResourceManager.GetString("LastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Локации.
        /// </summary>
        internal static string Locations {
            get {
                return ResourceManager.GetString("Locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Локации на тази Улица.
        /// </summary>
        internal static string LocationsInThisStreet {
            get {
                return ResourceManager.GetString("LocationsInThisStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Локации по обект.
        /// </summary>
        internal static string LocationsObj {
            get {
                return ResourceManager.GetString("LocationsObj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Влез.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to излез.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Меню.
        /// </summary>
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Създай Ордер.
        /// </summary>
        internal static string MenuCreate {
            get {
                return ResourceManager.GetString("MenuCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мобилен телефон.
        /// </summary>
        internal static string MobilePhone {
            get {
                return ResourceManager.GetString("MobilePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повече.
        /// </summary>
        internal static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to име.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нов статус.
        /// </summary>
        internal static string NewStatus {
            get {
                return ResourceManager.GetString("NewStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Няма документи към .
        /// </summary>
        internal static string NoDocumentIn {
            get {
                return ResourceManager.GetString("NoDocumentIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер.
        /// </summary>
        internal static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отворен код в .
        /// </summary>
        internal static string OpenSourceSystem {
            get {
                return ResourceManager.GetString("OpenSourceSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поръчка меню.
        /// </summary>
        internal static string OrderId {
            get {
                return ResourceManager.GetString("OrderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Политики.
        /// </summary>
        internal static string Policy {
            get {
                return ResourceManager.GetString("Policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пост.
        /// </summary>
        internal static string Post {
            get {
                return ResourceManager.GetString("Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подготовка.
        /// </summary>
        internal static string Preparation {
            get {
                return ResourceManager.GetString("Preparation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to цена.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Политики на поверителност .
        /// </summary>
        internal static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Промоция.
        /// </summary>
        internal static string Promotion {
            get {
                return ResourceManager.GetString("Promotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поръчка.
        /// </summary>
        internal static string Purchase {
            get {
                return ResourceManager.GetString("Purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрирай се.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ресторант.
        /// </summary>
        internal static string Restaurant {
            get {
                return ResourceManager.GetString("Restaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кандидатсвай за Партньор Ресторант .
        /// </summary>
        internal static string RestaurantApplay {
            get {
                return ResourceManager.GetString("RestaurantApplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Ресторанти чакащи за Одобрение .
        /// </summary>
        internal static string RestaurantWaitToApprove {
            get {
                return ResourceManager.GetString("RestaurantWaitToApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Търсене.
        /// </summary>
        internal static string Searching {
            get {
                return ResourceManager.GetString("Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изпратено на дата.
        /// </summary>
        internal static string SendDate {
            get {
                return ResourceManager.GetString("SendDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изпрати Email.
        /// </summary>
        internal static string SendEmail {
            get {
                return ResourceManager.GetString("SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email ще бъде изпратен от:.
        /// </summary>
        internal static string SendEmailWhit {
            get {
                return ResourceManager.GetString("SendEmailWhit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изпратено от мейл.
        /// </summary>
        internal static string SendGridEmail {
            get {
                return ResourceManager.GetString("SendGridEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Време на изпращане.
        /// </summary>
        internal static string SendTime {
            get {
                return ResourceManager.GetString("SendTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус в момента.
        /// </summary>
        internal static string StatusInThisMoment {
            get {
                return ResourceManager.GetString("StatusInThisMoment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Улица.
        /// </summary>
        internal static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Улици.
        /// </summary>
        internal static string Streets {
            get {
                return ResourceManager.GetString("Streets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Улици в тази Зона.
        /// </summary>
        internal static string StreetsInThisArea {
            get {
                return ResourceManager.GetString("StreetsInThisArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предмет.
        /// </summary>
        internal static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Време.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За.
        /// </summary>
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Днес.
        /// </summary>
        internal static string ToDay {
            get {
                return ResourceManager.GetString("ToDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общо.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Качи снимка.
        /// </summary>
        internal static string UploadImage {
            get {
                return ResourceManager.GetString("UploadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Качи Файл.
        /// </summary>
        internal static string UploudFile {
            get {
                return ResourceManager.GetString("UploudFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Качи нов документ .
        /// </summary>
        internal static string UploudNewDocument {
            get {
                return ResourceManager.GetString("UploudNewDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация за Юзър.
        /// </summary>
        internal static string UserData {
            get {
                return ResourceManager.GetString("UserData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Юзер.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Превозно средство.
        /// </summary>
        internal static string Vehichle {
            get {
                return ResourceManager.GetString("Vehichle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Превозни средства.
        /// </summary>
        internal static string Vehichles {
            get {
                return ResourceManager.GetString("Vehichles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Работна Зона.
        /// </summary>
        internal static string WorkingArea {
            get {
                return ResourceManager.GetString("WorkingArea", resourceCulture);
            }
        }
    }
}
